import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FibreFlow",
  description: "Generated by create next app",
};

import Sidebar from "../components/Sidebar";
import ThemeToggle from "../components/ThemeToggle";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950 text-gray-100 min-h-screen flex`}>
        <Sidebar />
        <main className="flex-1 flex flex-col min-h-screen">
          <header className="flex items-center p-4 border-b border-gray-800">
            <ThemeToggle />
          </header>
          <div className="p-6 flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
